server:
  port: 8888
spring:
  config:
    import: configserver:http://10.10.146.230:8888
  application:
    name: discovery-service
eureka:
  instance:
    hostname: 10.10.146.230
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/