FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /build/security-starter
COPY services/security-configuration-starter/pom.xml .
COPY services/security-configuration-starter/src ./src
RUN mvn install -DskipTests

WORKDIR /build/api-gateway
COPY services/api-gateway/pom.xml .
RUN mvn dependency:go-offline -B
COPY services/api-gateway/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /build/api-gateway/target/api-gateway-*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]