services:
  postgres_auth:
    image: postgres:16
    container_name: postgres_auth
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth_service
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    networks:
      - hotel-network
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres_user:
    image: postgres:16
    container_name: postgres_user
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    networks:
      - hotel-network
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  config_service:
    container_name: config_service
    build:
      context: ./config-server
      dockerfile: Dockerfile-jar
    ports:
      - "8888:8888"
    networks:
      - hotel-network
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SERVER_ADDRESS=0.0.0.0

  auth_service:
    container_name: auth_service
    build:
      context: ./auth-service
      dockerfile: Dockerfile-jar
    ports:
      - "8006:8006"
    networks:
      - hotel-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres_auth_data:
  postgres_user_data:

networks:
  hotel-network:
    driver: bridge