version: '3.8'

volumes:
  pgdata:
  redis_data:
  minio_data:



services:
  postgres:
    image: postgres:latest
    container_name: ms_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

  config-service:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: t1-internship/config-service:0.0.1-SNAPSHOT
    container_name: config-service
    network_mode: host
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/portner-boop/kon-repo-proj


  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    network_mode: host
    depends_on:
      - config-service
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=discovery-service
      - SERVER_PORT=8761
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

  places-service:
    build: ./places-service
    container_name: places-service
    ports:
      - "${PLACES_SERVICE_PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_HOST: "${EUREKA_HOST:-host.docker.internal}"
      EUREKA_PORT: "${EUREKA_PORT:-8761}"
      SERVER_PORT: "8080"

