version: '3.8'

volumes:
  pgdata:
  redis_data:

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: ms_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - backend
