version: '3.8'

volumes:
  pgdata:

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: ms_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
