services:
  db:
    image: postgres:15
    container_name: user_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=profiles
    volumes:
      - pg_users_profile:/var/lib/postgresql/data
volumes:
  pg_users_profile: