FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /build/shared
COPY services/shared/pom.xml .
COPY services/shared/src ./src
RUN mvn install -DskipTests

WORKDIR /build/auth-service
COPY services/auth-service/pom.xml .
RUN mvn dependency:go-offline -B
COPY services/auth-service/src ./src
RUN mvn clean install -DskipTests

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /build/auth-service/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]